[project]
name = "secrets_present"
version = "0.0.1"
description = "A Guardrails AI validator that detects and masks code secrets in LLM-generated text."
authors = [
    {name = "Guardrails AI", email = "contact@guardrailsai.com"}
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">= 3.8.1"
dependencies = [
    "guardrails-ai>=0.4.0",
    "detect-secrets>=1.4.0"
]

[project.optional-dependencies]
dev = [
    "pyright",
    "pytest",
    "ruff",
    "pytest-asyncio"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rP"
testpaths = [
    "test"
]
asyncio_mode = "auto"

[tool.pyright]
include = ["validator"]